services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: MyPass01
      POSTGRES_USER: myuser
      POSTGRES_DB: store
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
volumes:
  postgres: